### PR TITLE
Updating api endpoint

### PR DESCRIPTION
**Pull request by sialan**

### CODE REVIEW

**Comment by sialan** [comment]
Currently have the api outputting the raw fields returned from get_resume_recommendations(), get_next_recommendations(), and get_explore_recommendations() with a little bit of prettifying.

I can rejig things to pull more information and better match the fields in ka-lite/kalite/distributed/hbtemplates/contentrec/ ?

**Comment by rtibbles** [comment]
Main fields would be "title", "description", "path", "id", "kind". You can then append additional topic information to each of the fields.

I have just updated the handlebars templates to reflect this kind of schema. Let me know if you have any questions. Excited to get this merged!

**Comment by almgong** [comment]
I actually formatted the output already in the functions, should I not have? 

Also I am still working on reconstructing the tree! My old algorithm to do so was way too slow so I am trying an alternate way.

Will keep you guys updated

**Comment by rtibbles** [comment]
Going to merge this and let further iteration happen on the branch with @almgong and I.

**Pull request merged**
